import Head from 'next/head';
import Header from '../components/Header';
import Image from 'next/image';
import CheckoutProduct from '../components/CheckoutProduct';
import { useSelector } from 'react-redux';
import { selectItems, selectTotal } from '../slices/basketSlice';
import Currency from 'react-currency-formatter';
import { useSession } from 'next-auth/client';

function Checkout() {
  const [session] = useSession();
  const items = useSelector(selectItems);
  const total = useSelector(selectTotal);
  return (
    <div className="bg-gray-100">
      <Head>
        <title>Checkout</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      <main className="lg:flex max-w-screen-2xl mx-auto">
        {/* Left side */}
        <div className="flex-grow m-5 shadow-sm">
          <Image
            src="/advert.jpg"
            alt="Advertisement"
            width={1020}
            height={250}
            objectFit="contain"
          />

          <div className="flex flex-col p-5 space-y-10 bg-white">
            <h1 className="text-3xl border-b pb-4">
              {items.length === 0
                ? `Your basket is empty`
                : `Your shopping basket`}
            </h1>

            {items.map((item, index) => {
              return (
                <CheckoutProduct
                  key={index}
                  id={item.id}
                  title={item.title}
                  price={item.price}
                  description={item.description}
                  category={item.category}
                  image={item.image}
                />
              );
            })}
          </div>
        </div>

        {/* Right Side */}
        <div className="flex flex-col bg-white py-5 px-10 m-5">
          {items.length > 0 && (
            <>
              <h2>
                Subtotal ({items.length})
                <span>
                  <Currency quantity={total} currency="USD" />
                </span>
              </h2>

              <button
                className={`button mt-2 ${
                  !session &&
                  'from-gray-300 to-gray-500 border-gray border-gray-200 cursor-not-allowed'
                }`}
              >
                {!session ? 'Sign in to checkout' : 'Proceed to checkout'}
              </button>
            </>
          )}
        </div>
      </main>
    </div>
  );
}

export default Checkout;
