import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/Header'
import Banner from '../components/Banner'
import ProductFeed from '../components/ProductFeed'

export default function Home({ products }) {
  return (
    <div className="bg-gray-100">
      <Head>
        <title>Amazon</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

			<Header />

			<div className="max-w-7xl mx-auto">
				<Banner />
				
				<ProductFeed products={products} />
			</div>
    </div>
  )
}

export async function getServerSideProps(context) {
	const products = await fetch('https://fakestoreapi.com/products')
		.then((res) => res.json())

	return { 
		props: {
			products
		} 
	}
}